# Generated by Django 4.2.5 on 2023-10-10 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('possible_answers', models.ManyToManyField(to='risk_management.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management.answer')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management.meeting')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_management.question')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='questions',
            field=models.ManyToManyField(to='risk_management.question'),
        ),
    ]
