# Generated by Django 4.2.5 on 2023-10-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
