# Generated by Django 4.2.5 on 2023-10-13 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0002_alter_question_options_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='risk_management.answer'),
        ),
    ]
