# Generated by Django 4.2.5 on 2023-10-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0003_alter_response_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp UTC'),
        ),
    ]
