# Generated by Django 4.2.5 on 2023-10-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0005_answer_next_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='next_question',
        ),
    ]
