# Generated by Django 4.2.5 on 2023-10-23 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0006_remove_answer_next_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='conditional_answer',
            field=models.ForeignKey(blank=True, help_text="If set, this question will only show if the previous question's answer matches this answer.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_questions', to='risk_management.answer'),
        ),
    ]
