# Generated by Django 4.2.5 on 2023-10-25 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0007_question_conditional_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='conditional_answer',
            field=models.ForeignKey(blank=True, help_text='Contingent Answer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_questions', to='risk_management.answer'),
        ),
    ]
