# Generated by Django 4.2.5 on 2023-10-25 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0008_alter_answer_options_answer_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order', 'text']},
        ),
    ]
